syntax = "proto3";

package enrollment;

service EnrollmentService {
  rpc createEnrollment (CreateEnrollmentRequest) returns (EnrollmentResponse);
  rpc listEnrollmentsByStudent (ListEnrollmentsByStudentRequest) returns (ListEnrollmentsByStudentResponse);
}

message CreateEnrollmentRequest {
  string student_id = 1;
  int32 course_id = 2;
}

message EnrollmentResponse {
  string id = 1;
  string student_id = 2;
  int32 course_id = 3;
  string status = 4;
}

message ListEnrollmentsByStudentRequest {
  string student_id = 1;
}

message ListEnrollmentsByStudentResponse {
  repeated EnrollmentResponse enrollments = 1;
}